<?php

/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $inspection \Roave\DeveloperTools\Inspection\AggregateInspection */
/* @var $eventInspections \Roave\DeveloperTools\Inspection\EventInspection[] */
$eventInspections = $inspection->getInspectionData();

foreach ($eventInspections as $eventInspection) {
    $data = $eventInspection->getInspectionData();

    echo '<dl>'
        . '<dt>Name</dt>'
        . '<dd>' . $this->escapeHtml($data['name']) . '</dd>'
        . '<dt>Time</dt>'
        . '<dd>' . $this->escapeHtml(number_format($data['time'], 6, '.', '')) . '</dd>'
        . '<dt>Memory</dt>'
        . '<dd>' . $this->escapeHtml(number_format($data['memory'] / 1024, 2, '.', '')) . ' Kb</dd>'
        . '<dt>Target</dt>'
        . '<dd>'
        . $this->escapeHtml(is_object($data['target']) ? get_class($data['target']) : gettype($data['target']))
        . '</dd>'
        . '</dl>';
}
