<?php
/*
 * Copyright (c) 2005-2014, Zend Technologies USA, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *
 *     * Redistributions in binary form must reproduce the above copyright notice,
 *       this list of conditions and the following disclaimer in the documentation
 *       and/or other materials provided with the distribution.
 *
 *     * Neither the name of Zend Technologies USA, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from this
 *       software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* This file was imported from https://github.com/zendframework/ZendDeveloperTools */

/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $inspection \Roave\DeveloperTools\Mvc\Inspection\ConfigInspection */

$icon = base64_encode(file_get_contents(__DIR__ . '/../../../../asset/exception-toolbar-tab.png'));
$data = $inspection->getInspectionData();

?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/jpeg;base64,<?= $icon; ?>" alt="Profiler Errors">
        <span class="zdt-toolbar-info"><?= count($data); ?></span>
    </div>
    <div class="zdt-toolbar-detail">
        <span class="zdt-toolbar-info zdt-toolbar-info-heading">Errors</span>
        <?php foreach ($data as $i => $exception) { ?>
            <span class="zdt-toolbar-info">
                <strong title="Exception Number"><?= $i; ?></strong>
                <code title="Exception Classname"><?= $this->escapeHtml($exception['class']); ?></code>
                <span title="Exception Code">(<?= $this->escapeHtml($exception['code']); ?>):</span>
                <span title="Exception Message"><?= $this->escapeHtml($exception['message']); ?></span>
            </span>
        <?php } ?>
    </div>
</div>
<?php

/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $inspection \Roave\DeveloperTools\Inspection\ExceptionInspection */

echo '<div class="exception">'
    . '<strong>'
    . $this->escapeHtml($inspection->getInspectionData()[0]['class'])
    . '</strong>: '
    . $this->escapeHtml($inspection->getInspectionData()[0]['message'])
    . '</div>';
