<?php

use Roave\DeveloperTools\Inspection\TimeInspection;

/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $inspection TimeInspection */

$icon = base64_encode(file_get_contents(__DIR__ . '/../../../../asset/time-toolbar-tab.png'));
$data = $inspection->getInspectionData();

?>
<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="data:image/jpeg;base64,<?= $icon; ?>" alt="Execution Time">
        <span class="zdt-toolbar-info"><?=
            $data[TimeInspection::PARAM_START];
        ?> ~ <?=
            $data[TimeInspection::PARAM_END];
        ?></span>
    </div>
</div>
