<?php
/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $tabs \Zend\View\Model\ModelInterface[] */

echo '<style type="text/css">' . file_get_contents(__DIR__ . '/../../../asset/toolbar.css') . '</style>';
?>
<!-- START Zend Developer Toolbar -->
<div id="zend-developer-toolbar">
<?php

foreach ($tabs as $tab) {
    foreach ($tab as $inspectionResults) {
        echo $this->render($inspectionResults);
    }
}

?>

    <a id="zdf-toolbar-toggle" class="zdf-toolbar-hide-button" href="javascript:void(0);"></a>
</div>
<!-- END Zend Developer Toolbar -->
