<?php

use Roave\DeveloperTools\Renderer\BaseAggregateInspectionRenderer;

/* @var $this \Zend\View\Renderer\PhpRenderer */
/* @var $detailModels \Zend\View\Model\ModelInterface[][][] */

?>
<div id="zend-developer-tools-details">
    <?php

    foreach ($detailModels as $detailModelGroup) {
        foreach ($detailModelGroup as $inspectionResults) {
            echo $this->render($inspectionResults[BaseAggregateInspectionRenderer::PARAM_MODEL]);
        }
    }

    ?>
</div>
